name: watcher

repo:
  link: "github.com/DoormatIka/doormats-home"
  extract:
    to: "/tmp"
  web:
    original: "/web"
    to: ""
  server:
    original: "/server"
    to: ""
  watcher:
    original: "/watcher"
    to: ""
